version: '3.1'

services:
  postgres:
    image: postgres:14-alpine
    container_name: tinder_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tinder
    ports:
      - "5433:5432"

  app:
    image: wofyor/tinder:1.0
    container_name: app
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/tinder
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - postgres
